name: flutter_payment_gateways
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_credit_card: ^4.0.1
  font_awesome_flutter: ^10.7.0
  flutter_stripe: ^10.2.0
  dio: ^5.5.0+1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  flutter_paypal_payment: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/
